// projectPractice/03-react/react-vite-blog/src/components/GlobalTips/index.jsx
import React, { Component } from 'react'
import './index.less'
import { SmileOutlined, CloseOutlined } from '@ant-design/icons'
class Index extends Component {
  constructor () {
    super()
    this.state = {
    }
  }
  render () {
    const {
      dailyData,
      children,
      extra
    } = this.props
    return (
      <div className='global-tips'>
        {/*tips*/}
        <div className="title-tips">
          <SmileOutlined />
          {children}
          '伟波前端'，将是一个美好的邂逅哦!
          {
            dailyData && (
              <span className="daily-tip">({dailyData})</span>
            )
          }
          {extra}
          <CloseOutlined  className="close-icon"/>
        </div>
        {/*github*/}
        <div className="github">
      <span className="github-title">
        github
      </span>
          <span className="github-star">200</span>
        </div>
      </div>
    )
  }
}
export default Index

// projectPractice/02-vue/vue-blog/src/components/GlobalTips/index.vue
<template>
  <div>
    <!--    tips-->
    <div class="title-tips">
      <img class="smile-icon" src="~@/static/images/smile.png">
      <slot></slot>：'伟波前端'，将是一个美好的邂逅哦!
      <span v-if="dailyData" class="daily-tip">({{dailyData}})</span>
      <slot name="extra"></slot>
      <img class="close-icon" src="~@/static/images/close.png">
    </div>
    <!--    github-->
    <div class="github">
      <span class="github-title">
        <img class="smile-icon" src="~@/static/images/smile.png">
        github
      </span>
      <span class="github-star">200</span>
    </div>
  </div>
</template>

<script src="./index.js"></script>

<style scoped lang="less">
@import "./index";
</style>
