// projectPractice/03-react/react-vite-blog/src/components/GlobalFooter/index.jsx
import React, { Component, PureComponent } from 'react'
import './index.less'
class List extends PureComponent {
  constructor () {
    super()
    this.state = {
    }
  }
  render () {
    const {
    } = this.state
    return (
      <div className="global-footer footer">
        <p className="copy-name">
          Power & Designed by
          <a className="name" href="../../index/index.html">weiboqianduan</a>
        </p>
        <p className="copy-num">
          © 2017
          <a href="../../index/index.html">陕ICP备17015350号</a>
        </p>
      </div>
    )
  }
}
export default List

// projectPractice/02-vue/vue-blog/src/components/GlobalFooter/index.vue
<template>
  <div class="footer">
    <p class="copy-name">
      Power & Designed by
      <a class="name" href="../../index/index.html">weiboqianduan</a>
    </p>
    <p class="copy-num">
      © 2017
      <a href="../../index/index.html">陕ICP备17015350号</a>
    </p>
  </div>
</template>

<script src="./index.js"></script>

<style scoped lang="less">
@import "./index";
</style>
