// projectPractice/03-react/react-vite-blog/src/pages/index/index.jsx
import React, { Component } from 'react'
import './index.less'
import { pageIndexConstantData } from '@/constant'
class Index extends Component {
  constructor () {
    super()
    this.state = {
      ...pageIndexConstantData,
      timer: null,
      backgroundImage: 'http://images.static.liuweibo.cn/image/index/zhoulou.jpg'
    }
  }
  getRandom () {
    return Math.random() * this.state.BG_INDEX.length | 0
  }
  handleTarget = (item) => () => {
    console.log(item)
    this.props.history.push('/list')
  }
  init () {
    const defaultIndexBg = 0
    const timer = setInterval(() => {
      let random = this.getRandom()
      if (random === defaultIndexBg) {
        random = this.getRandom()
      }
      this.setState({
        backgroundImage: this.state.BG_INDEX[random].value
      })
    }, 3000)
    this.setState({
      timer
    })
  }
  componentDidMount () {
    console.log('componentDidMount')
    this.init()
  }
  componentWillUnmount () {
    console.log('componentWillUnmount')
    clearInterval(this.state.timer)
  }
  render () {
    const {
      backgroundImage, title, subTitle,
      footer, titleList
    } = this.state
    return (
      <div className="container-rapper"
           style={{ backgroundImage: `url(${backgroundImage})` }}
      >
        <div className="container">
          {/*头部标题*/}
          <div className="header">
            <h1>{title}</h1>
            <div className="sub-title">{subTitle}</div>
          </div>
          {/*主题内容*/}
          <div className="content">
            <ul className="list">
              {
                titleList.map((item, index) => {
                  return (
                    <li
                      className="item"
                      key={index}
                      onClick={this.handleTarget(item)}
                    >
                      <a>》》{item.title}</a>
                    </li>
                  )
                })
              }
            </ul>
          </div>
          {/*页脚*/}
          <div className="footer">
            {footer}
          </div>
        </div>
      </div>
    )
  }
}
export default Index

// projectPractice/02-vue/vue-blog/src/pages/index/index.vue
<template>
  <div class="container-rapper"
       :style="{backgroundImage: `url(${backgroundImage})`}"
  >
    <div class="container">
      <!--  头部标题-->
      <div class="header">
        <h1>{{ title }}</h1>
        <div class="sub-title">{{ subTitle }}</div>
      </div>
      <!--  主题内容-->
      <div class="content">
        <ul class="list">
          <li class="item"
              :class="{
              'last-item': index === titleList.length - 1
            }"
              :key="index"
              v-for="(item, index) in titleList">
<!--            <router-link v-bind:to="'list'">》》{{ item.title }}</router-link>-->
            <a @click="handleTarget(item)">》》{{ item.title }}</a>
          </li>
        </ul>
      </div>
      <!--  页脚-->
      <div class="footer">
        {{ footer }}
      </div>
    </div>
  </div>
</template>

<script>
import { pageIndexConstantData } from '@/constant'
export default {
  data () {
    return {
      ...pageIndexConstantData,
      backgroundImage: 'http://images.static.liuweibo.cn/image/index/zhoulou.jpg'
    };
  },
  created () {},
  mounted () {
    this.init()
  },
  methods: {
    init () {
      const defaultIndexBg = 0
      setInterval(()=>{
        let random = this.getRandom()
        if (random === defaultIndexBg) {
          random = this.getRandom()
        }
        this.backgroundImage = this.BG_INDEX[random].value
      }, 3000)
    },
    getRandom () {
      return Math.random() * this.BG_INDEX.length | 0
    },
    handleTarget (item) {
      this.$router.push('/list')
    }
  }
}
</script>

<style scoped lang="less">
.container-rapper {
  min-height: 100vh;
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  transition: All 2s ease;
}
.container {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 800px;
  /*margin-top: 100px; todo 超出隐藏*/
  font-size: 14px;
  color: white;
  background-color: rgba(0, 0, 0, .3);
  border-radius: 20px;
  transform: translate(-50%, -50%);
}


.header {
  padding-top: 26px;
  margin-bottom: 38px;
}

h1 {
  font-size: 18px;
  text-align: center;
  color: white;
}

.sub-title {
  margin-top: 16px;
  text-align: center;
}

.content {
  margin-left: 20px;
  margin-right: 20px;
  padding-top: 22px;
  padding-bottom: 12px;
  border-top: 1px solid #ffffff;
  border-bottom: 1px solid #ffffff;
}
.list{
  width: 690px;
  margin: 0 auto;
}
.item {
  font-size: 14px;
  padding: 5px 2px;
  margin-bottom: 15px;
  background-color: rgba(0, 0, 0, .5);
  border-radius: 6px;
}
.item{
  a{
    color: white;
    text-decoration: none;
    cursor: pointer;
  }
}
.last-item{
  margin-bottom: 0;
}
.footer {
  padding: 10px 20px;
  text-align: right;
}

</style>
