// projectPractice/02-vue/vue-blog/src/App.vue
<template>
  <div id="app">
    <ListPage />
  </div>
</template>

<script>
import IndexPage from './pages/index/index'
import ListPage from './pages/list/index.vue'

export default {
  name: 'App',
  components: {
    // IndexPage,
    ListPage
  }
}
</script>

<style>
@import "~@/assets/reset.less";
</style>

// projectPractice/03-react/react-vite-blog/src/App.jsx
import React, { useState } from 'react'
import './App.css'
import '@/assets/reset.less'
import '@/assets/common.less'
import Index from '@/pages/index'
import List from '@/pages/list'
import { BrowserRouter as Router, Route, Link, Switch} from "react-router-dom";
const NoMatch = ({ location }) => (
  <div>
    <h3>
      No match for <code>{location.pathname}</code>
    </h3>
  </div>
);
function App() {
  return (
    <Router>
      <Switch>
        <Route exact path="/" component={Index} />
        <Route path="/list" component={List} />
        <Route component={NoMatch} />
      </Switch>
    </Router>
  )
}

export default App
